name: fit_planner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http_parser: ^4.0.2
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  http: ^1.6.0

  # ===== FIREBASE (VERSÕES CORRETAS PARA FLUTTER 3.38.3) =====
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # ===== OUTROS =====
  image_picker: ^1.2.1
  google_generative_ai: ^0.4.7
  url_launcher: ^6.2.0

  # ===== ÍCONES PREMIUM =====
  phosphor_flutter: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - imagens/logo.png
    - imagens/water_bottle.png
    - imagens/frango.png
    - imagens/pao.png
    - imagens/abacate.png
    - imagens/ovo.png
    - imagens/salmao.png
    - imagens/whey.png
    - imagens/carboidratos.png
    - imagens/azeite.png
    - imagens/amendoa.png
    - imagens/vitaminas_e_minerais.png
    - imagens/suplemento.png
    - imagens/creatina.png
    - imagens/gifs/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "imagens/logo.png"
