// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsHOaKflfNg156mgrsWfzfNY4Ye5yckA',
    appId: '1:959317964769:web:690208325e031961f9c4a0',
    messagingSenderId: '959317964769',
    projectId: 'fit-planner-app-01',
    authDomain: 'fit-planner-app-01.firebaseapp.com',
    storageBucket: 'fit-planner-app-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUx3oqATtdpgly46bm0kWtxerpT94KRE4',
    appId: '1:959317964769:android:2dc9f4be61658c6cf9c4a0',
    messagingSenderId: '959317964769',
    projectId: 'fit-planner-app-01',
    storageBucket: 'fit-planner-app-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8YAgSsFpevf4lWDfvcr7DRu_N7OquPHo',
    appId: '1:959317964769:ios:700deb8acb549a21f9c4a0',
    messagingSenderId: '959317964769',
    projectId: 'fit-planner-app-01',
    storageBucket: 'fit-planner-app-01.firebasestorage.app',
    iosBundleId: 'com.example.fitPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8YAgSsFpevf4lWDfvcr7DRu_N7OquPHo',
    appId: '1:959317964769:ios:700deb8acb549a21f9c4a0',
    messagingSenderId: '959317964769',
    projectId: 'fit-planner-app-01',
    storageBucket: 'fit-planner-app-01.firebasestorage.app',
    iosBundleId: 'com.example.fitPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADsHOaKflfNg156mgrsWfzfNY4Ye5yckA',
    appId: '1:959317964769:web:1393c015a7fb478bf9c4a0',
    messagingSenderId: '959317964769',
    projectId: 'fit-planner-app-01',
    authDomain: 'fit-planner-app-01.firebaseapp.com',
    storageBucket: 'fit-planner-app-01.firebasestorage.app',
  );
}
